name: geira_icons
description: Geira Icons is a constantly growing family of icons. Each icon is designed considering visual uniformity and balance.
homepage: https://icons.geira.com
version: 2.2.0

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Geira Icons
      fonts:
        - asset: lib/fonts/GeiraIcons-Regular.ttf