name: geira_icons
description: Geira Icons is a constantly growing family of icons. Each icon is designed considering visual uniformity and balance.
homepage: https://icons.geira.com
version: 2.1.4

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Geira Icons
      fonts:
        - asset: lib/fonts/GeiraIcons-Regular.ttf

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.1.2"
