library geira_icons;

import 'package:flutter/widgets.dart';
import 'package:geira_icons/icons_map.dart';

class GIcons {
  static const IconData none = _GIconData(0xE000);
  static const IconData pencil = _GIconData(0xE001);
  static const IconData brush = _GIconData(0xE002);
  static const IconData wifi = _GIconData(0xE004);
  static const IconData chat = _GIconData(0xE005);
  static const IconData notifications = _GIconData(0xE007);
  static const IconData notifications_off = _GIconData(0xE008);
  static const IconData notifications_active = _GIconData(0xE009);
  static const IconData send = _GIconData(0xE00A);
  static const IconData person = _GIconData(0xE00B);
  static const IconData people = _GIconData(0xE00C);
  static const IconData no_show = _GIconData(0xE00D);
  static const IconData person_status = _GIconData(0xE00E);
  static const IconData chart = _GIconData(0xE013);
  static const IconData restore = _GIconData(0xE01F);
  static const IconData undo = _GIconData(0xE02A);
  static const IconData update = _GIconData(0xE02B);
  static const IconData refresh = _GIconData(0xE02C);
  static const IconData chevron_up = _GIconData(0xE02D);
  static const IconData chevron_right = _GIconData(0xE02E);
  static const IconData chevron_down = _GIconData(0xE02F);
  static const IconData chevron_left = _GIconData(0xE03A);
  static const IconData arrow_up = _GIconData(0xE03B);
  static const IconData arrow_right = _GIconData(0xE03C);
  static const IconData arrow_down = _GIconData(0xE03D);
  static const IconData arrow_left = _GIconData(0xE03E);
  static const IconData delete = _GIconData(0xE03F);
  static const IconData volume = _GIconData(0xE04C);
  static const IconData volume_low = _GIconData(0xE04D);
  static const IconData volume_medium = _GIconData(0xE04E);
  static const IconData volume_up = _GIconData(0xE04F);
  static const IconData volume_off = _GIconData(0xE05A);
  static const IconData hearing = _GIconData(0xE05B);
  static const IconData mic = _GIconData(0xE05C);
  static const IconData mic_off = _GIconData(0xE05D);
  static const IconData recording = _GIconData(0xE05E);
  static const IconData no_audio = _GIconData(0xE05F);
  static const IconData refresh_audio = _GIconData(0xE06A);
  static const IconData load_audio = _GIconData(0xE06B);
  static const IconData play_arrow = _GIconData(0xE06D);
  static const IconData pause = _GIconData(0xE06E);
  static const IconData stop = _GIconData(0xE06F);
  static const IconData skip_next = _GIconData(0xE07A);
  static const IconData skip_previous = _GIconData(0xE07B);
  static const IconData record = _GIconData(0xE07C);
  static const IconData previous = _GIconData(0xE08C);
  static const IconData next = _GIconData(0xE08D);
  static const IconData cloud = _GIconData(0xE097);
  static const IconData upload = _GIconData(0xE098);
  static const IconData up_balls = _GIconData(0xE099);
  static const IconData download = _GIconData(0xE09A);
  static const IconData rearrange = _GIconData(0xE09B);
  static const IconData slider = _GIconData(0xE09D);
  static const IconData list = _GIconData(0xE09E);
  static const IconData sidebar_close = _GIconData(0xE09F);
  static const IconData sidebar_open = _GIconData(0xE0A0);
  static const IconData open_menu = _GIconData(0xE0A1);
  static const IconData close_menu = _GIconData(0xE0A2);
  static const IconData down_menu = _GIconData(0xE0A3);
  static const IconData up_menu = _GIconData(0xE0A4);
  static const IconData launch = _GIconData(0xE0A5);
  static const IconData exit_to_app = _GIconData(0xE0A6);
  static const IconData menu = _GIconData(0xE0A7);
  static const IconData more_vert = _GIconData(0xE0A8);
  static const IconData more_horiz = _GIconData(0xE0A9);
  static const IconData cell_phone = _GIconData(0xE0B8);
  static const IconData phone = _GIconData(0xE0B9);
  static const IconData home = _GIconData(0xE0BA);
  static const IconData language = _GIconData(0xE0BB);
  static const IconData url = _GIconData(0xE0BC);
  static const IconData lang = _GIconData(0xE0BD);
  static const IconData lang_help = _GIconData(0xE0BE);
  static const IconData map = _GIconData(0xE0BF);
  static const IconData country = _GIconData(0xE0C0);
  static const IconData navigation = _GIconData(0xE0C1);
  static const IconData notification = _GIconData(0xE0C8);
  static const IconData flag = _GIconData(0xE0C9);
  static const IconData place = _GIconData(0xE0CA);
  static const IconData mail = _GIconData(0xE0CB);
  static const IconData award = _GIconData(0xE0E7);
  static const IconData trophy = _GIconData(0xE0E8);
  static const IconData shopping_cart = _GIconData(0xE0F5);
  static const IconData bet = _GIconData(0xE0F6);
  static const IconData add_balance = _GIconData(0xE0F7);
  static const IconData payment = _GIconData(0xE0F8);
  static const IconData bill = _GIconData(0xE0F9);
  static const IconData deal = _GIconData(0xE0FA);
  static const IconData gift = _GIconData(0xE0FB);
  static const IconData time = _GIconData(0xE0FC);
  static const IconData chronometer = _GIconData(0xE0FD);
  static const IconData time_record = _GIconData(0xE0FE);
  static const IconData folder = _GIconData(0xE111);
  static const IconData folder_open = _GIconData(0xE112);
  static const IconData folder_add = _GIconData(0xE113);
  static const IconData folder_special = _GIconData(0xE114);
  static const IconData folder_delete = _GIconData(0xE115);
  static const IconData page = _GIconData(0xE117);
  static const IconData book = _GIconData(0xE118);
  static const IconData test = _GIconData(0xE119);
  static const IconData flash_cards = _GIconData(0xE11A);
  static const IconData pdf = _GIconData(0xE124);
  static const IconData doc = _GIconData(0xE125);
  static const IconData jpg = _GIconData(0xE126);
  static const IconData png = _GIconData(0xE127);
  static const IconData chevron_tr = _GIconData(0xE130);
  static const IconData chevron_dr = _GIconData(0xE131);
  static const IconData chevron_dl = _GIconData(0xE132);
  static const IconData chevron_tl = _GIconData(0xE133);
  static const IconData check = _GIconData(0xE134);
  static const IconData check_outline = _GIconData(0xE135);
  static const IconData checked = _GIconData(0xE136);
  static const IconData unchecked = _GIconData(0xE137);
  static const IconData rb_checked = _GIconData(0xE139);
  static const IconData rb_unchecked = _GIconData(0xE13A);
  static const IconData match = _GIconData(0xE13B);
  static const IconData temperature = _GIconData(0xE163);
  static const IconData odd_even = _GIconData(0xE164);
  static const IconData hot = _GIconData(0xE165);
  static const IconData cold = _GIconData(0xE166);
  static const IconData hot_cold = _GIconData(0xE167);
  static const IconData delta = _GIconData(0xE168);
  static const IconData delta_cold = _GIconData(0xE169);
  static const IconData delta_hot = _GIconData(0xE16A);
  static const IconData sum = _GIconData(0xE16B);
  static const IconData sum_hot = _GIconData(0xE16C);
  static const IconData sum_cold = _GIconData(0xE16D);
  static const IconData face_id = _GIconData(0xE177);
  static const IconData scan = _GIconData(0xE17F);
  static const IconData retry_scan = _GIconData(0xE180);
  static const IconData ar_horiz = _GIconData(0xE181);
  static const IconData ar_vert = _GIconData(0xE182);
  static const IconData parking = _GIconData(0xE19F);
  static const IconData bike = _GIconData(0xE1A0);
  static const IconData walk = _GIconData(0xE1A1);
  static const IconData girl = _GIconData(0xE1A2);
  static const IconData boy = _GIconData(0xE1A3);
  static const IconData disabled = _GIconData(0xE1A4);
  static const IconData photo_id = _GIconData(0xE1A5);
  static const IconData politician = _GIconData(0xE1CC);
  static const IconData bull = _GIconData(0xE1CD);
  static const IconData cow = _GIconData(0xE1CE);
  static const IconData verified = _GIconData(0xE1E1);
  static const IconData verified_user = _GIconData(0xE1E2);
  static const IconData lock = _GIconData(0xE1E3);
  static const IconData lock_open = _GIconData(0xE1E4);
  static const IconData advertising = _GIconData(0xE1FA);
  static const IconData no_advertising = _GIconData(0xE1FB);
  static const IconData video = _GIconData(0xE1FC);
  static const IconData question_answer = _GIconData(0xE201);
  static const IconData info = _GIconData(0xE202);
  static const IconData help = _GIconData(0xE203);
  static const IconData error = _GIconData(0xE204);
  static const IconData visibility = _GIconData(0xE205);
  static const IconData visibility_off = _GIconData(0xE206);
  static const IconData thumb_up = _GIconData(0xE207);
  static const IconData thumb_down = _GIconData(0xE208);
  static const IconData favorite_border = _GIconData(0xE209);
  static const IconData favorite = _GIconData(0xE20A);
  static const IconData favorite_dislike = _GIconData(0xE20B);
  static const IconData share = _GIconData(0xE20C);
  static const IconData bookmark = _GIconData(0xE20D);
  static const IconData star_border = _GIconData(0xE20E);
  static const IconData star_half = _GIconData(0xE20F);
  static const IconData star = _GIconData(0xE210);
  static const IconData rate = _GIconData(0xE211);
  static const IconData ticket = _GIconData(0xE212);
  static const IconData game = _GIconData(0xE213);
  static const IconData lotto = _GIconData(0xE214);
  static const IconData cabala = _GIconData(0xE215);
  static const IconData clover = _GIconData(0xE216);
  static const IconData sad_face = _GIconData(0xE22D);
  static const IconData happy_face = _GIconData(0xE22E);
  static const IconData dictation = _GIconData(0xE22F);
  static const IconData oral = _GIconData(0xE230);
  static const IconData event_available = _GIconData(0xE231);
  static const IconData upcoming = _GIconData(0xE232);
  static const IconData past = _GIconData(0xE233);
  static const IconData event = _GIconData(0xE234);
  static const IconData no_event = _GIconData(0xE235);
  static const IconData month = _GIconData(0xE236);
  static const IconData dashboard = _GIconData(0xE23A);
  static const IconData campaign = _GIconData(0xE23B);
  static const IconData unpin = _GIconData(0xE243);
  static const IconData push_pin = _GIconData(0xE244);
  static const IconData search = _GIconData(0xE245);
  static const IconData search_page = _GIconData(0xE246);
  static const IconData search_person = _GIconData(0xE247);
  static const IconData search_number = _GIconData(0xE248);
  static const IconData camera = _GIconData(0xE254);
  static const IconData no_image = _GIconData(0xE255);
  static const IconData images = _GIconData(0xE256);
  static const IconData remove = _GIconData(0xE257);
  static const IconData remove_circle = _GIconData(0xE258);
  static const IconData add = _GIconData(0xE259);
  static const IconData add_circle = _GIconData(0xE25A);
  static const IconData close = _GIconData(0xE25B);
  static const IconData cancel = _GIconData(0xE25C);
  static const IconData filter = _GIconData(0xE25D);
  static const IconData edit = _GIconData(0xE25E);
  static const IconData settings = _GIconData(0xE25F);
  static const IconData save = _GIconData(0xE260);
  static const IconData add_square = _GIconData(0xE262);
  static const IconData remove_square = _GIconData(0xE263);
  static const IconData more_less = _GIconData(0xE264);
  static const IconData total = _GIconData(0xE265);
  static const IconData number = _GIconData(0xE266);
  static const IconData television = _GIconData(0xE26B);
  static const IconData store = _GIconData(0xE26C);
  static const IconData drink = _GIconData(0xE26D);
  static const IconData bulb_number = _GIconData(0xE279);
  static const IconData bulb_on = _GIconData(0xE27A);
  static const IconData bulb = _GIconData(0xE27B);
  static const IconData cashier = _GIconData(0xE27C);
  static const IconData afternoon = _GIconData(0xE285);
  static const IconData evening = _GIconData(0xE286);
  static const IconData full_square = _GIconData(0xE287);
  static const IconData full_dot = _GIconData(0xE288);
  static const IconData brightness_1 = _GIconData(0xE289);
  static const IconData brightness_2 = _GIconData(0xE28A);
  static const IconData brightness_3 = _GIconData(0xE28B);
  static const IconData brightness_4 = _GIconData(0xE28C);
  static const IconData brightness_5 = _GIconData(0xE28D);
  static const IconData brightness_6 = _GIconData(0xE28E);
  static const IconData brightness_7 = _GIconData(0xE28F);
  static const IconData facebook = _GIconData(0xE291);
  static const IconData twitter = _GIconData(0xE292);
  static const IconData youtube = _GIconData(0xE293);
  static const IconData instagram = _GIconData(0xE294);
  static const IconData linkedin = _GIconData(0xE295);
  static const IconData github = _GIconData(0xE2A0);
  static const IconData gitlab = _GIconData(0xE2A1);
  static const IconData npm = _GIconData(0xE2A2);
  static const IconData apple_logo = _GIconData(0xE2A3);
  static const IconData facebook_logo = _GIconData(0xE2A4);
  static const IconData google_logo = _GIconData(0xE2A5);
  static const IconData whatsapp_logo = _GIconData(0xE2A6);
  static const IconData x_logo = _GIconData(0xE2A7);
  static const IconData logo = _GIconData(0xE2AF);

  static IconData? fromString(String key) {
    int? codePoint = iconMap[key];
    if (codePoint == null) return null;
    return _GIconData(codePoint);
  }

  IconData? operator [](String key) {
    int? codePoint = iconMap[key];
    if (codePoint == null) return null;
    return _GIconData(codePoint);
  }

  static List<String> getIconsName() {
    return iconMap.keys.toList();
  }
}

class _GIconData extends IconData {
  const _GIconData(int codePoint)
      : super(
          codePoint,
          fontFamily: 'Geira Icons',
          fontPackage: 'geira_icons',
        );
}
